### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by pkasson** [danielsaidi/OnboardingKit#20]
First, thanks for putting this kit in the public - much needed things for MacOS and Swift.

The build fails with the following detail:

`Static stored properties not supported in generic types` in Tutorial+Demo.swift.

Also, when running the demo, you need to add the https://github.com/danielsaidi/OnboardingKit.git package to the project.

**Comment by danielsaidi** [comment]
Hi @pkasson 

Thank you for reaching out regarding this.

This is the result of me changing the tutorial type to a generic type. Although I want it that way, it makes it hard to extend it with app-specific types :/ 

I will take a look and hopefully come up with a solution, but I'm currently very busy with another project that I have to wrap up first.

**Comment by danielsaidi** [comment]
This should be fixed in the latest version.
